x-app-base: &app-base
  user: 0:0
  networks:
    - infra
  restart: unless-stopped

x-zookeeper-base: &zookeeper-base
  <<: *app-base
  image: confluentinc/cp-zookeeper:7.4.4

x-kafka-base: &kafka-base
  <<: *app-base
  image: confluentinc/cp-kafka:7.4.4
  depends_on:
    - zookeeper-1
    - zookeeper-2
    - zookeeper-3

x-zookeeper-environment: &zookeeper-environment
  ZOOKEEPER_SERVER_1: zookeeper-1:2888:3888
  ZOOKEEPER_SERVER_2: zookeeper-2:2888:3888
  ZOOKEEPER_SERVER_3: zookeeper-3:2888:3888

  ZOOKEEPER_TICK_TIME: 2000
  ZOOKEEPER_INIT_LIMIT: 5
  ZOOKEEPER_SYNC_LIMIT: 2
  ZOOKEEPER_SECURE_CLIENT_PORT: 2281
  ZOOKEEPER_SERVER_CNXN_FACTORY: org.apache.zookeeper.server.NettyServerCnxnFactory

  ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
  ZOOKEEPER_SSL_KEYSTORE_ALIAS: zookeeper

  ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/zookeeper/certs/truststore.jks

  ZOOKEEPER_SSL_KEYSTORE_PASSWORD: changeit
  ZOOKEEPER_SSL_KEY_PASSWORD: changeit
  ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: changeit

  ZOOKEEPER_SSL_CLIENT_ENABLE: true
  ZOOKEEPER_SSL_CLIENT_AUTH: need

  KAFKA_OPTS: >-
    -Djava.security.auth.login.config=/etc/zookeeper/configs/zookeeper.sasl.jaas.conf
    -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    -Dzookeeper.allowSaslFailedClients=false
    -Dzookeeper.requireClientAuthScheme=sasl

x-kafka-environment: &kafka-environment
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
  KAFKA_DELETE_TOPIC_ENABLE: false
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281/kafka-brokers
  KAFKA_ZOOKEEPER_SASL_CLIENT: 'true'
  KAFKA_ZOOKEEPER_SET_ACL: 'true'
  KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: true
  KAFKA_ZOOKEEPER_SECURITY_PROTOCOL: SASL_SSL
  KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
  KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/certs/truststore.jks
  KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: changeit
  KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: changeit

  KAFKA_SSL_CLIENT_AUTH: required
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
  KAFKA_SSL_KEYSTORE_TYPE: PKCS12
  KAFKA_SSL_TRUSTSTORE_TYPE: JKS
  KAFKA_SSL_TRUSTSTORE_FILENAME: truststore.jks

  KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka_creds
  KAFKA_SSL_KEY_CREDENTIALS: kafka_creds
  KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka_creds

  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  KAFKA_LISTENER_NAME_SASL_SSL_SSL_CLIENT_AUTH: need
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_CLIENT_AUTH: required

  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL,EXTERNAL:SASL_SSL
  KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
  KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
  KAFKA_SUPER_USERS: User:kafka_server_admin
  KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"

services:
  vault:
    <<: *app-base
    build:
        context: ./vault
        dockerfile: Dockerfile
    container_name: vault_certs_generator
    hostname: vault
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_config:/vault/config
      - vault_certs:/vault/certs
      - vault_secrets:/vault/secrets
      - vault_storage:/vault/storage
    entrypoint: vault server -config /vault/config/config.hcl

  zookeeper-1:
    <<: *zookeeper-base
    container_name: zookeeper-1
    hostname: zookeeper-1
    environment:
      <<: *zookeeper-environment
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/zookeeper/certs/zookeeper-1.p12
    volumes:
      - zookeeper_log_1:/var/lib/zookeeper/log
      - zookeeper_data_1:/var/lib/zookeeper/data
      - vault_certs:/etc/zookeeper/certs
      - ./zookeeper/configs/zookeeper.sasl.jaas.conf:/etc/zookeeper/configs/zookeeper.sasl.jaas.conf

  zookeeper-2:
    <<: *zookeeper-base
    container_name: zookeeper-2
    hostname: zookeeper-2
    environment:
      <<: *zookeeper-environment
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/zookeeper/certs/zookeeper-2.p12
    volumes:
      - zookeeper_log_2:/var/lib/zookeeper/log
      - zookeeper_data_2:/var/lib/zookeeper/data
      - vault_certs:/etc/zookeeper/certs
      - ./zookeeper/configs/zookeeper.sasl.jaas.conf:/etc/zookeeper/configs/zookeeper.sasl.jaas.conf

  zookeeper-3:
    <<: *zookeeper-base
    container_name: zookeeper-3
    hostname: zookeeper-3
    environment:
      <<: *zookeeper-environment
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/zookeeper/certs/zookeeper-3.p12
    volumes:
      - zookeeper_log_3:/var/lib/zookeeper/log
      - zookeeper_data_3:/var/lib/zookeeper/data
      - vault_certs:/etc/zookeeper/certs
      - ./zookeeper/configs/zookeeper.sasl.jaas.conf:/etc/zookeeper/configs/zookeeper.sasl.jaas.conf
  
  zoonavigator:
    <<: *app-base
    image: elkozmon/zoonavigator
    container_name: zoonavigator
    hostname: zoonavigator
    ports:
      - 9443:9443
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      HTTP_PORT: disabled
      HTTPS_PORT: 9443
      ZK_CLIENT_SECURE: true
      ZK_SASL_CLIENT: true
      ZK_SASL_CLIENT_CONFIG: Client
      ZK_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
      ZK_SSL_KEYSTORE_PATH: /etc/zookeeper/certs/client.p12
      ZK_SSL_TRUSTSTORE_PATH: /etc/zookeeper/certs/truststore.jks
      ZK_SSL_TRUSTSTORE_PASSWORD: changeit
      ZK_SSL_KEYSTORE_PASSWORD: changeit

      SSL_KEYSTORE_PATH: /etc/zookeeper/certs/zoonavigator.p12
      SSL_KEYSTORE_TYPE: PKCS12
      SSL_KEYSTORE_PASSWORD: changeit

      JAVA_JAAS_LOGIN_CONFIG: /etc/zookeeper/configs/zookeeper.sasl.client.jaas.conf
      JAVA_TOOL_OPTIONS: >- 
        -Djava.security.auth.login.config=/etc/zookeeper/configs/zookeeper.sasl.client.jaas.conf
    volumes:
      - vault_certs:/etc/zookeeper/certs
      - ./zookeeper/configs/zookeeper.sasl.client.jaas.conf:/etc/zookeeper/configs/zookeeper.sasl.client.jaas.conf
  
  kafka-1:
    <<: *kafka-base
    container_name: kafka-1
    hostname: kafka-1
    environment:
      <<: *kafka-environment
      KAFKA_BROKER_ID: 1
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-1.p12
      KAFKA_LISTENERS: SASL_SSL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-1:9093
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka-1.p12
    volumes:
      - kafka_1:/var/lib/kafka/data-1
      - vault_certs:/etc/kafka/certs
      - vault_secrets:/etc/kafka/secrets
      - ./kafka/configs/kafka_server_jaas.conf:/etc/kafka/secrets/kafka_server_jaas.conf
      - ./kafka/configs/adminclient-configs.conf:/etc/kafka/secrets/adminclient-configs.conf

  kafka-2:
    <<: *kafka-base
    container_name: kafka-2
    hostname: kafka-2
    environment:
      <<: *kafka-environment
      KAFKA_BROKER_ID: 2
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-2.p12
      KAFKA_LISTENERS: SASL_SSL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-2:9093
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka-2.p12
    volumes:
      - kafka_2:/var/lib/kafka/data-2
      - vault_certs:/etc/kafka/certs
      - vault_secrets:/etc/kafka/secrets
      - ./kafka/configs/kafka_server_jaas.conf:/etc/kafka/secrets/kafka_server_jaas.conf
      - ./kafka/configs/adminclient-configs.conf:/etc/kafka/secrets/adminclient-configs.conf

  kafka-3:
    <<: *kafka-base
    container_name: kafka-3
    hostname: kafka-3
    environment:
      <<: *kafka-environment
      KAFKA_BROKER_ID: 3
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-3.p12
      KAFKA_LISTENERS: SASL_SSL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-3:9093
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka-3.p12
    volumes:
      - kafka_3:/var/lib/kafka/data-3
      - vault_certs:/etc/kafka/certs
      - vault_secrets:/etc/kafka/secrets
      - ./kafka/configs/kafka_server_jaas.conf:/etc/kafka/secrets/kafka_server_jaas.conf
      - ./kafka/configs/adminclient-configs.conf:/etc/kafka/secrets/adminclient-configs.conf

  ui:
    <<: *app-base
    image: provectuslabs/kafka-ui:v0.7.0
    container_name: ui
    hostname: ui
    volumes:
      - vault_certs:/etc/ui/certs
    ports:
      - 8080:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-1:9093,kafka-2:9093,kafka-3:9093
      KAFKA_CLUSTERS_0_NAME: kafka

      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL

      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_TYPE: PKCS12

      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /etc/ui/certs/truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /etc/ui/certs/client.p12

      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: changeit

      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="ui" password="ui_password";

volumes:
  vault_config:
  vault_certs:
  vault_secrets:
  vault_storage:
  zookeeper_log_1:
  zookeeper_data_1:
  zookeeper_log_2:
  zookeeper_data_2:
  zookeeper_log_3:
  zookeeper_data_3:
  kafka_1:
  kafka_2:
  kafka_3:

networks:
  infra: