services:
  vault:
    build:
        context: ./vault
        dockerfile: Dockerfile
    container_name: vault_certs_generator
    hostname: vault
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_config:/vault/config
      - vault_certs:/vault/certs
      - vault_secrets:/vault/secrets
      - vault_storage:/vault/storage
    entrypoint: vault server -config /vault/config/config.hcl

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2281:2281
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SECURE_CLIENT_PORT: 2281
      ZOOKEEPER_SERVER_CNXN_FACTORY: org.apache.zookeeper.server.NettyServerCnxnFactory

      ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      ZOOKEEPER_SSL_KEYSTORE_ALIAS: zookeeper

      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/zookeeper/certs/zookeeper.p12
      ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/zookeeper/certs/kafka-truststore.jks

      ZOOKEEPER_SSL_KEYSTORE_PASSWORD: changeit
      ZOOKEEPER_SSL_KEY_PASSWORD: changeit
      ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: changeit

      ZOOKEEPER_SSL_CLIENT_ENABLE: true
      ZOOKEEPER_SSL_CLIENT_AUTH: need

      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
        -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dzookeeper.allowSaslFailedClients=false
        -Dzookeeper.requireClientAuthScheme=sasl
    volumes:
      - zookeeper_log:/var/lib/zookeeper/log
      - zookeeper_data:/var/lib/zookeeper/data
      - vault_certs:/etc/zookeeper/certs
      - vault_secrets:/etc/zookeeper/secrets
      - ./zookeeper/configs/zookeeper.sasl.jaas.conf:/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf

volumes:
  vault_config:
  vault_certs:
  vault_secrets:
  vault_storage:
  zookeeper_log:
  zookeeper_data:

networks:
  infra: