x-app-base: &app-base
  networks:
    - infra
  restart: unless-stopped

x-zookeeper-base: &zookeeper-base
  <<: *app-base
  image: confluentinc/cp-zookeeper:7.4.4

x-zookeeper-environment: &zookeeper-environment
  ZOOKEEPER_SERVER_1: zookeeper-1:2888:3888
  ZOOKEEPER_SERVER_2: zookeeper-2:2888:3888
  ZOOKEEPER_SERVER_3: zookeeper-3:2888:3888

  ZOOKEEPER_TICK_TIME: 2000
  ZOOKEEPER_INIT_LIMIT: 5
  ZOOKEEPER_SYNC_LIMIT: 2
  ZOOKEEPER_CLIENT_PORT: 2181
  ZOOKEEPER_SECURE_CLIENT_PORT: 2281
  ZOOKEEPER_SERVER_CNXN_FACTORY: org.apache.zookeeper.server.NettyServerCnxnFactory

  ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
  ZOOKEEPER_SSL_KEYSTORE_ALIAS: zookeeper

  ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/zookeeper/certs/zookeeper.p12
  ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/zookeeper/certs/kafka-truststore.jks

  ZOOKEEPER_SSL_KEYSTORE_PASSWORD: changeit
  ZOOKEEPER_SSL_KEY_PASSWORD: changeit
  ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: changeit

  ZOOKEEPER_SSL_CLIENT_ENABLE: true
  ZOOKEEPER_SSL_CLIENT_AUTH: need

  KAFKA_OPTS: >-
    -Djava.security.auth.login.config=/etc/zookeeper/configs/zookeeper.sasl.jaas.conf
    -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    -Dzookeeper.allowSaslFailedClients=false
    -Dzookeeper.requireClientAuthScheme=sasl

services:
  vault:
    <<: *app-base
    build:
        context: ./vault
        dockerfile: Dockerfile
    container_name: vault_certs_generator
    hostname: vault
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_config:/vault/config
      - vault_certs:/vault/certs
      - vault_secrets:/vault/secrets
      - vault_storage:/vault/storage
    entrypoint: vault server -config /vault/config/config.hcl

  zookeeper-1:
    <<: *zookeeper-base
    container_name: zookeeper-1
    hostname: zookeeper-1
    environment:
      <<: *zookeeper-environment
      ZOOKEEPER_SERVER_ID: 1
    volumes:
      - zookeeper_log_1:/var/lib/zookeeper/log
      - zookeeper_data_1:/var/lib/zookeeper/data
      - vault_certs:/etc/zookeeper/certs
      - ./zookeeper/configs/zookeeper.sasl.jaas.conf:/etc/zookeeper/configs/zookeeper.sasl.jaas.conf

  zookeeper-2:
    <<: *zookeeper-base
    container_name: zookeeper-2
    hostname: zookeeper-2
    environment:
      <<: *zookeeper-environment
      ZOOKEEPER_SERVER_ID: 2
    volumes:
      - zookeeper_log_2:/var/lib/zookeeper/log
      - zookeeper_data_2:/var/lib/zookeeper/data
      - vault_certs:/etc/zookeeper/certs
      - ./zookeeper/configs/zookeeper.sasl.jaas.conf:/etc/zookeeper/configs/zookeeper.sasl.jaas.conf

  zookeeper-3:
    <<: *zookeeper-base
    container_name: zookeeper-3
    hostname: zookeeper-3
    environment:
      <<: *zookeeper-environment
      ZOOKEEPER_SERVER_ID: 3
    volumes:
      - zookeeper_log_3:/var/lib/zookeeper/log
      - zookeeper_data_3:/var/lib/zookeeper/data
      - vault_certs:/etc/zookeeper/certs
      - ./zookeeper/configs/zookeeper.sasl.jaas.conf:/etc/zookeeper/configs/zookeeper.sasl.jaas.conf
  
  zoonavigator:
    <<: *app-base
    image: elkozmon/zoonavigator
    restart: always
    container_name: zoonavigator
    hostname: zoonavigator
    ports:
      - 9443:9443
    environment:
      HTTP_PORT: disabled
      HTTPS_PORT: 9443
      ZK_SSL_TRUSTSTORE_PATH: /etc/zookeeper/certs/kafka-truststore.jks
      ZK_SSL_TRUSTSTORE_PASSWORD: changeit
      SSL_KEYSTORE_PATH: /etc/zookeeper/certs/kafka-client.p12
      SSL_KEYSTORE_PASSWORD: changeit
      SSL_KEYSTORE_TYPE: PKCS12
      ZK_SASL_CLIENT: "true"
      ZK_SASL_CLIENT_CONFIG: "Client"
      JAVA_JAAS_LOGIN_CONFIG: /etc/zookeeper/configs/zookeeper.sasl.client.jaas.conf
      JAVA_TOOL_OPTIONS: "-Djava.security.auth.login.config=/etc/zookeeper/configs/zookeeper.sasl.client.jaas.conf -Djava.security.auth.debug=all"
    volumes:
      - vault_certs:/etc/zookeeper/certs
      - ./zookeeper/configs/zookeeper.sasl.client.jaas.conf:/etc/zookeeper/configs/zookeeper.sasl.client.jaas.conf

volumes:
  vault_config:
  vault_certs:
  vault_secrets:
  vault_storage:
  zookeeper_log_1:
  zookeeper_data_1:
  zookeeper_log_2:
  zookeeper_data_2:
  zookeeper_log_3:
  zookeeper_data_3:

networks:
  infra: