# Generated by Django 3.2.16 on 2025-12-29 16:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Up to 20 symbols', max_length=20, verbose_name='Compra')),
                ('description', models.TextField(help_text='Up to 200 symbols', max_length=200, verbose_name='Description')),
                ('price', models.FloatField(help_text='Positive float value', validators=[django.core.validators.MaxValueValidator(5000.0), django.core.validators.MinValueValidator(0.1)], verbose_name='Price')),
                ('ingressed_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='gastos.brand', verbose_name='Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='gastos.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(related_name='compras', to='gastos.Tag', verbose_name='Теги')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Titular')),
            ],
            options={
                'verbose_name_plural': 'Cecipes',
                'ordering': ('-ingressed_at',),
                'default_related_name': 'compras',
            },
        ),
    ]
