# Generated by Django 3.2.16 on 2025-12-30 09:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Good')),
            ],
            options={
                'verbose_name_plural': 'Goods',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompraGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Amount')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.compra', verbose_name='Compra')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.good', verbose_name='Good')),
            ],
            options={
                'verbose_name_plural': 'Compra goods',
                'unique_together': {('compra', 'good')},
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='goods',
            field=models.ManyToManyField(related_name='compras', through='gastos.CompraGood', to='gastos.Good', verbose_name='Goods'),
        ),
    ]
