# Generated by Django 3.2.16 on 2025-12-30 15:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_auto_20251230_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompraProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Amount')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.compra', verbose_name='Compra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Compra products',
                'unique_together': {('compra', 'product')},
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='products',
            field=models.ManyToManyField(related_name='compras', through='gastos.CompraProduct', to='gastos.Product', verbose_name='Goods'),
        ),
    ]
