# Generated by Django 3.2.16 on 2026-01-02 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_auto_20260102_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1, help_text='Positive float value', validators=[django.core.validators.MaxValueValidator(5000.0), django.core.validators.MinValueValidator(0.1)], verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Up to 20 symbols', max_length=20, unique=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Up to 20 symbols', max_length=20, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Up to 20 symbols', max_length=20, unique=True, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Up to 20 symbols', max_length=20, unique=True, verbose_name='Tag'),
        ),
    ]
