# Generated by Django 3.2.16 on 2026-01-02 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0010_auto_20260102_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='compraproduct',
            name='price',
            field=models.FloatField(default=1, help_text='Positive float value', validators=[django.core.validators.MaxValueValidator(5000.0), django.core.validators.MinValueValidator(0.1)], verbose_name='Price'),
            preserve_default=False,
        ),
    ]
