# Generated by Django 3.2.16 on 2026-01-03 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0012_alter_compra_ingressed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='ingressed_at',
            field=models.DateTimeField(default='2026-01-03 10:03', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='compraproduct',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Amount'),
        ),
    ]
