route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "telegram"
receivers:
  - name: 'telegram'
    telegram_configs:
    - api_url: https://api.telegram.org
      bot_token: '7462989477:AAGV3-5sWCek9h_LYgqs9bNNqLtTAU4tZxY'
      chat_id: 301352346