# Generated by Django 3.2.16 on 2025-12-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_auto_20251230_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'default_related_name': 'compras', 'ordering': ('-ingressed_at',), 'verbose_name_plural': 'Compras'},
        ),
    ]
