# Generated by Django 3.2.16 on 2025-12-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_alter_compra_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='goods',
        ),
        migrations.DeleteModel(
            name='CompraGood',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
