# Generated by Django 3.2.16 on 2026-01-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_auto_20251230_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='name',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='titular',
        ),
    ]
