# Generated by Django 3.2.16 on 2026-01-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0011_auto_20260102_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='ingressed_at',
            field=models.DateTimeField(default='2026-01-03 09:22', verbose_name='Created'),
        ),
    ]
